### ISSUE TITLE
Generate pretty printed config file

### ISSUE THREAD

**Issue by mateusz-gozdek-sociomantic** [whefter/puppet-syncthing#11]
Current changes in `config.xml` differ from changes made from GUI. That would be nice, if puppet-generated config would be the same as that, generated from GUI.

**Comment by whefter** [comment]
Hi,

I'm a sucker for pretty-printed configuration myself, but as this is essentially a ton of work that adds no stability or features, I won't be undertaking any work in this direction. As long as Syncthing swallows the config.xml, I'm fine with it.

**Comment by invidian** [comment]
This is actually not that much work, as you probably think. I'm also able to do that for you.
I made that already in my fork and it's working pretty well. Part of it is in 23112f411946d966f539524c58cc1f5dcd50211d and b0b207dee23aa9416f878beea61546f22ecf645a.

Advantage of pretty formatted config file is increased readability, which is important, when you don't use GUI and you want to see what config you currently have.
