### ISSUE TITLE
Make sure that instance home directory exists

### ISSUE THREAD

**Issue by mateusz-gozdek-sociomantic** [whefter/puppet-syncthing#15]
and it has correct permissions.

This directory should be managed by this module. Probably, managing instance home may be optional.

**Comment by invidian** [comment]
After reviewing other puppet modules, I decided, that end user should take care of creating instance directory. Feel free to close that one.

**Comment by whefter** [comment]
I added an option to create it, defaulting to false. It will probably be useful in some situations, but this way, users will have to opt-in.

**Comment by invidian** [comment]
Cool, that is good solution for that in my opinion, thanks.
