### ISSUE TITLE
gui_password and gui_password_salt parameters

### ISSUE THREAD

**Issue by darkpixel** [whefter/puppet-syncthing#22]
I have tried setting:

```
gui_user => 'admin'
gui_password => 'test'
```
and I have tried:
```
gui_user => 'admin'
gui_password_salt => '$2a$10$xFoDNvS6eG9wYRFB1a4u/eZoNWG.3qothMdVjmLubQGhgPT9V08X6'  #'test'
```

I have even tried:
```
gui_user => 'admin'
gui_password => 'test'
gui_password_salt => '$2a$10$xFoDNvS6eG9wYRFB1a4u/eZoNWG.3qothMdVjmLubQGhgPT9V08X6'
```

I am not able to log in with 'admin' and 'test'.  The documentation isn't really clear on the different password parameters.  Am I missing something?

**Comment by whefter** [comment]
Hi,

I agree, the information was somewhat vague. In your case, the salt you pasted is the full BCrypt hash, not only the salt (an example salt was already present in the old README).

Please see the new documentation for gui_password and gui_password_salt for more information.

Regards,

**Comment by darkpixel** [comment]
Thanks for the pointers.  I got it working.
