### ISSUE TITLE
allow (apt) repository management to be optional

### ISSUE THREAD

**Issue by igalic** [whefter/puppet-syncthing#3]
This will make it so that the module is more useful to a broader range of people who
- built their own packages
- manage their (apt) repositories centrally
- use a different version of puppetlabs/apt

**Comment by whefter** [comment]
Agreed. I'll try and get around to this fix this weekend.

**Comment by whefter** [comment]
Forgot to reference this in the commit, but I finally got around to fixing this. Sorry for the massive delay. It should be possible to disable repository management now.

**Comment by igalic** [comment]
noworries!

**Comment by bigbrozer** [comment]
Hello !
I've added a new `package_name` attribute to `syncthing` class in b1b5bba. That adds support for those who built their own packages. I will test it tonight and create the pull request afterwards.

**Comment by whefter** [comment]
I've merged the PR, thanks!
