### ISSUE TITLE
Global discovery: unsupported scheme 

### ISSUE THREAD

**Issue by brentclark** [whefter/puppet-syncthing#32]
Goodday

Im not sure if its because of the version im running (i.e. 0.14.28).
But on the dashboard Im getting 'Notice :  2017-05-19 10:00:12: Global discovery: unsupported scheme '

HTH
Regards
Brent Clark

**Comment by bigbigbang** [comment]
I'm running the same version, without any problem, but I have specified (and setup) my own GlobalDiscoveryServer.
What have you specified in the manifest ? 
If you want to use the defaults Global discovery don't set anything. 
If you want to disable the default one and set your own , set it like this :
# Override or set arbitrary options
      options     => {
        'listenAddress' => 'tcp4://0.0.0.0:19000',
        'startBrowser'  => 'false',
        'globalAnnounceServer'  => '', # disable defaults globalAnnounceServers
        'globalAnnounceServer'  => $announce_node, # add your private this way
        'globalAnnounceServer2' => $announce_node2, # add a second this way
As I have worked on it, please let me know if you still have any problem.

**Comment by whefter** [comment]
This looks like a configuration problem, not a module problem. Since there hasn't been a reply, I'm closing this issue. Feel free to re-open.
