### ISSUE TITLE
Can't folder resource

### ISSUE THREAD

**Issue by amateo** [whefter/puppet-syncthing#33]
I'm using the last version of the forge module. I'm trying to create a folder, but I can't. I get the error:

> Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Invalid relationship: Augeas[configure instance /etc/syncthing/puppet folder puppet_environment] { notify => Service[syncthing] }, because Service[syncthing] doesn't seem to be in the catalog

I think the problem could be that in _manifests/folder.pp_ the code is:
```
  augeas { "configure instance ${home_path} folder ${id}":
      incl    => $instance_config_xml_path,
      lens    => 'Xml.lns',
      context => "/files${instance_config_xml_path}/configuration",
      changes => $changes,

      notify  => [
>>    # Service["syncthing ${instance_name}"],
        Exec["restart syncthing instance ${instance_name}"],
        Service['syncthing'],
      ],

      require => [
        Exec["create syncthing instance ${home_path}"],
      ],
    }
```
but the service declaration is commented in _manifests/service.pp_:
```
  #  service { 'syncthing':
  #    ensure  => running,
  #    enable  => true,
  #    require => [
  #      File['/etc/init.d/syncthing']
  #    ],
  #  }
```
I'm not sure if you should remove notifying the service or changing to another name.

**Comment by amateo** [comment]
I have patched the code. See #34

**Comment by whefter** [comment]
Thank you, I have merged the PR.
