### ISSUE TITLE
(optional) installation of bcrypt gem

### ISSUE THREAD

**Issue by igalic** [whefter/puppet-syncthing#4]
in the default puppet-agent 4.2.x installation, there is no `bcrypt` gem, so the parser function won't quite work.

it would be nice to have a two parameters

``` puppet
  $manage_bcrypt = false,
  $gem_provider  = 'gem',
```

which can be used to control the installation of bcrypt.

**Comment by igalic** [comment]
so i just realized that this is only useful on the puppet server. or, well, on each machine when you're running masterless (which i am)

**Comment by whefter** [comment]
Currently the bcrypt function is not used, is it causing trouble for you anyway?

**Comment by nerdlich** [comment]
It is, here: https://github.com/whefter/puppet-syncthing/blob/90b60f213141efa6d57a5d134d38a8de87e986f4/manifests/instance.pp#L72

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: no such file to load -- bcrypt

**Comment by darkpixel** [comment]
+1

```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: cannot load such file -- bcrypt
```

**Comment by whefter** [comment]
I've added a more sensible error message in case the puppetmaster can't find the bcrypt gem. Unfortunately I can't currently see any way around this since the gem really is required on the puppetmaster, so I'm closing this issue. Thanks.
