### ISSUE TITLE
Unable to synchronize folder between more than two devices

### ISSUE THREAD

**Issue by mateusz-gozdek-sociomantic** [whefter/puppet-syncthing#8]
Augeas first adds an entry to file and then it replace it with a new one. This is clearly not a correct behaviour.

**Comment by mateusz-gozdek-sociomantic** [comment]
I prepared a fix for this. It's this [branch](https://github.com/mateusz-gozdek-sociomantic/puppet-syncthing/tree/fix-folder-device-class). I will raise an PR after merging #13 and #14.

**Comment by whefter** [comment]
After looking at this for a bit and playing around with Augeas, it turns out there's an easy fix for it. The latest commit fixes this. I'll add some comments to your PR as well.
